export const routes = {
  home: "/",
  markets: "/markets",
  trades: "/trades",
  orders: "/orders",
  portfolio: "/portfolio",
  wallet: "/wallet",
  aiSignals: "/ai-signals",
  aiChat: "/ai-chat",
  watchlist: "/watchlist",
  news: "/news",
  calendar: "/calendar",
  profile: "/profile",
  plans: "/profile/plans",
  verification: "/profile/verification",
  security: "/profile/security",
  about: "/about",
  invite: "/invite",
  settings: "/settings",
  help: "/help",
  faq: "/faq",
  contact: "/contact",
  notifications: "/notifications",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
